# Generated by Django 4.2.21 on 2025-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_chatroom_organization_message_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='tasktype',
            name='color',
            field=models.CharField(default='#ffd6d1', max_length=7),
        ),
    ]
